### ISSUE TITLE
code release?

### ISSUE THREAD

**Issue by Dibbidy** [boschresearch/VSTAR#1]

**Comment by YumengLi007** [comment]
Hi @Dibbidy , thanks for your interests! I'm currently working on the code release. Please stay tuned and your patience is greatly appreciated :)

**Comment by olliacc** [comment]
any update?

**Comment by Aibecool174** [comment]
?

**Comment by YumengLi007** [comment]
Hi all, 
the initial code has been released. Thank you all for your patience!
